server/config/routes.rb
Rails.application.routes.draw do
  #resources :outings

  
  #devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }


  namespace :api, :defaults => {:format => 'json'} do

    devise_for :users, controllers: { registration: 'registrations'}, :path => 'auth'
  	resources :outings
    resources :users
  end

  #resources :users

  #post 'outings/join/:id', to: 'outings#join'
  #post 'outings/unjoin/:id', to: 'outings#unjoin'

  #get 'pages/index'

  #root 'pages#index'
end

server/app/models/outing.rb
class Outing < ActiveRecord::Base
	belongs_to :creator, class_name: "User"
	has_many :players, class_name: "User", :through => :player_outing
	has_many :player_outings

	validates :wanted_num_players, presence: true, numericality: { only_integer: true, :greater_than =>	 0 }
	validates :title, presence: true
	validates :start_time, presence: true
	validates :course, presence: true
end

server/app/controllers/api/outings_controller.rb
class Api::OutingsController < Api::BaseController
  def index
    render json: { :outings => Outing.where("start_time >= :now", :now => Time.now) }
  end

  def create
  	if @user.present?
		outing = Outing.new(outing_params)
	    outing.creator = @user
	    player_outing = outing.player_outings.new
	    player_outing.user = @user
	    player_outing.outing = outing

	    if outing.save
			render json: { :outing => outing } , status: :created 
	    else
	        render json: { :errors => outing.errors} , status: :unprocessable_entity 
	    end
	else
		render json: { :error => "you must be authenticated"}, status: :unauthorized
	end
  end

  private 
  def outing_params
  	  json_params = ActionController::Parameters.new(JSON.parse(request.body.read))
      json_params.require(:outing).permit(:start_time, :course, :title, :description, :wanted_num_players)
    end
end

server/app/controllers/outings_controller.rb
class OutingsController < ApplicationController
  before_action :set_outing, only: [:show, :edit, :update, :destroy, :join, :unjoin]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]

  # GET /outings
  # GET /outings.json
  def index
    @outings = Outing.where("start_time >= :now", :now => Time.now)
  end

  # GET /outings/1
  # GET /outings/1.json
  def show

  end

  # GET /outings/new
  def new
    @outing = Outing.new
  end

  # GET /outings/1/edit
  def edit
  end

  def join
    player_outing = @outing.player_outings.new
    player_outing.outing = @outing
    player_outing.user = current_user
    respond_to do |format|
      if player_outing.save
        format.html { redirect_to @outing, notice: 'Successfully joined outing.' }
        format.json { render :show, status: :created, location: @outing }
      else
        format.html { redirect_to @outing, notice: 'Failed to join outing.' }
        format.json { render json: @outing.errors, status: :unprocessable_entity }
      end
    end
  end

  def unjoin
      respond_to do |format|
        if @outing.creator == current_user
          format.html { redirect_to @outing, alert: 'You can\'t quit from an outing you created!' }
          format.json { render json: { errors: 'You can\'t quit from an outing you created!' }, status: :unprocessable_entity }
        else
          player_outing = @outing.player_outings.select{|player_outing| player_outing.user == current_user}.first
          if player_outing.destroy
            format.html { redirect_to @outing, notice: 'Successfully quit from outing.' }
            format.json { render :show, status: :created, location: @outing }
          else
            format.html { redirect_to @outing, alert: 'Failed to quit from outing.' }
            format.json { render json: @outing.errors, status: :unprocessable_entity }
          end
        end
      end
  end

  # POST /outings
  # POST /outings.json
  def create
    @outing = Outing.new(outing_params)
    @outing.creator = current_user
    @player_outing = @outing.player_outings.new
    @player_outing.user = current_user
    @player_outing.outing = @outing

    respond_to do |format|
      if @outing.save
        format.html { redirect_to @outing, notice: 'Outing was successfully created.' }
        format.json { render :show, status: :created, location: @outing }
      else
        format.html { render :new }
        format.json { render json: @outing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outings/1
  # PATCH/PUT /outings/1.json
  def update
    respond_to do |format|
      if @outing.update(outing_params)
        format.html { redirect_to @outing, notice: 'Outing was successfully updated.' }
        format.json { render :show, status: :ok, location: @outing }
      else
        format.html { render :edit }
        format.json { render json: @outing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outings/1
  # DELETE /outings/1.json
  def destroy
    @outing.destroy
    respond_to do |format|
      format.html { redirect_to outings_url, notice: 'Outing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_outing
      @outing = Outing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def outing_params
      params.require(:outing).permit(:start_time, :course, :title, :description, :wanted_num_players)
    end

    def check_user
       if current_user != @outing.creator
          redirect_to root_url, alert: "Sorry, you cannot edit this outing"
      end
    end
end

server/app/helpers/outings_helper.rb
module OutingsHelper
end

server/app/views/outings/_form.html.erb
<%= simple_form_for(@outing) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.input :title, class: 'form-control',  placeholder: "Title"  %>
  	<%= f.input :description, class: 'form-control',  placeholder: "Description"  %>
    <%= f.input :start_time, class: 'form-control',  placeholder: "Start Time"  %>
    <%= f.input :course, class: 'form-control',  placeholder: "Course Name"  %>
    <%= f.input :wanted_num_players, class: 'form-control',  placeholder: "Wanted Players"  %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary'%>
  </div>
<% end %>

server/app/views/outings/edit.html.erb
<h1>Editing Outing</h1>

<%= render 'form' %>

<%= link_to 'Show', @outing %> |
<%= link_to 'Back', outings_path %>

server/app/views/outings/index.html.erb
<h1>Listing outings</h1>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Start time</th>
      <th>Course</th>
      <th>Number of players</th>
      <th>Number of open slots</th>
      <th>Creator</th>
      <th>Actions</th>
    </tr>
</thead>

  <tbody>
    <% @outings.each do |outing| %>
      <tr>
        <td><%= link_to outing.title, outing_path(outing) %></td>
        <td><%= outing.description %></td>
        <td><%= outing.start_time %></td>
        <td><%= outing.course %></td>
        <td><%= outing.player_outings.count %></td>
        <td><%= outing.wanted_num_players - outing.player_outings.count %></td>
        <td><%= link_to outing.creator.display_name, user_path(outing.creator)%></td>
        <% if outing.player_outings.select {|o| o.user == current_user}.empty? %>
          <td><%= link_to 'Join', { controller: "outings", action: "join", id: outing}, method: :post, class: 'btn btn-primary' %></td><td></td><td></td>
        <% else %>
          <td><%= link_to 'Unjoin', { controller: "outings", action: "unjoin", id: outing}, method: :post, class: 'btn btn-danger' %></td><td></td><td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Outing', new_outing_path %>

server/app/views/outings/new.html.erb
<div class='row'>
<div class='col-sm-4'></div>
<div class='col-sm-5'>
<h1>New Outing</h1>

<%= render 'form' %>

<%= link_to 'Back', outings_path %>
</div>
<div class='col-sm-4'></div>
</div>

server/app/views/outings/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Details</h2>
<h3><%= @outing.title %></h3>
<p>
<h5><%= @outing.description %></h5>
<p>
  <strong>Start time:</strong>
  <%= @outing.start_time %>
</p>

<p>
  <strong>Course:</strong>
  <%= @outing.course %>
</p>

<h3>Players</h3>

<h4>Players wanted: <%= @outing.wanted_num_players %>, Players found <%= @outing.player_outings.count %></h4>
<ul>
<% @outing.player_outings.each do |player_outing| %>
 	<li><%= link_to player_outing.user.display_name, user_path(player_outing.user) %></li>
<% end %>
</ul>


<%= link_to 'Edit', edit_outing_path(@outing) %> |
<%= link_to 'Back', outings_path %>