server/config/routes.rb
Rails.application.routes.draw do
  #resources :outings

  
  #devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }


  namespace :api, :defaults => {:format => 'json'} do

    devise_for :users, controllers: { registration: 'registrations'}, :path => 'auth'
  	resources :outings
    resources :users
  end

  #resources :users

  #post 'outings/join/:id', to: 'outings#join'
  #post 'outings/unjoin/:id', to: 'outings#unjoin'

  #get 'pages/index'

  #root 'pages#index'
end

server/app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Golf With Me", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">    
      <ul class="nav navbar-nav navbar-right">
      	<% if user_signed_in? %>
          <li><%= link_to "Outings", outings_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "My Profile(#{current_user.display_name})", edit_user_registration_path %></li>
      		<li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
	      <% else %>
	    	  <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Login <span class="caret"></span></a>
	          <ul class="dropdown-menu" role="menu">
	            <li><%= link_to "With Email", new_user_session_path %></li>
	            <li><%= link_to "With Facebook", user_omniauth_authorize_path(:facebook) %></li>
	            <li class="divider"></li>
	            <li><%= link_to "Sign Up", new_user_registration_path %></li>
	          </ul>
	        </li>
	      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Golfwithme</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<%= render 'layouts/header' %>

<% flash.each do |name, msg| %>
<div class='alert text-center alert-<%= name == "notice" ? "success" : "error" %>'>
<a class='close' data-dismiss="alert">x</a>
<%= msg %>
</div>
<% end %>



<div class='container'>
	<%= yield %>
</div>

</body>
</html>